### ISSUE TITLE
Inputting system IDs with a space at the end causes the system to not load

### ISSUE THREAD

**Issue by pkmemorysystem** [z0w13/pkstatus#2]
I figured out why the systems never stop loading! If you input the system ID with a space at the end (comon if you're copy-pasting) it doesn't want to load. Sanitizing the input by removing spaces should fix the issue I think

![Screenshot 2024-02-23 184054](https://github.com/z0w13/pkstatus/assets/143729274/7774060e-50eb-49c2-9ac5-80a04cd6d462)

**Comment by Echo-noen** [comment]
(This is my main account sorry) Also this makes it so you can't delete that member in the manage section. You can fix it right now by deleting "systems" in localStorage but that deletes everyone which is _inconvenient_

**Comment by z0w13** [comment]
Whitespace input issue has been fixed in [31c2973](https://github.com/z0w13/pkstatus/commit/31c297328631970819015760dd60cd20435acb57) but I don't really have any kind of migration system set up yet for data in persisted storage so for now it is gonna have to be either manually editing the key in localstorage or wiping the data
